import Image from "next/image";
import Coupon from "../components/Coupon";
import pages from "../data/pages.json";
import {cleanSeoText} from "../lib/seoText";

const picks=["electric-engineer","electric-industrial-engineer","electric-construction-engineer","fire-equipment-engineer","public-enterprise-electric"];
const guides=["electric-engineer-beginner","electric-engineer-written","electric-engineer-practical","electric-engineer-cbt","certificate-study-plan","lecture-selection-guide"];

export default function Home(){return <main>
 <section className="homeHero"><div><span className="eyebrow">2026 자격증 수강 정보</span><h1>엔지니어랩 할인코드 <em>e1572</em><br/>전기·소방 자격증 수강 가이드</h1><p>전기기사·전기산업기사·전기공사기사·소방설비기사 강의와 교수별 특징, 실제 강의 화면, CBT와 공부법을 확인한 뒤 수강 전 할인코드 e1572 적용 여부를 살펴보세요.</p><Coupon/></div><div className="heroImage"><Image src="/images/prof-jo.jpg" alt="엔지니어랩 전기기사 강의 안내 자료" fill priority sizes="(max-width:800px) 100vw, 45vw"/></div></section>
 <section className="section"><div className="sectionTitle"><span>자격증별 강의 가이드</span><h2>준비하는 시험에 맞춰 먼저 확인하세요</h2><p>시험별로 필기·실기 구성과 공부 순서가 다릅니다. 목표 자격증을 선택해 강좌 선택 기준과 학습 방법을 확인할 수 있습니다.</p></div><div className="cards">{picks.map(s=>{const p=(pages as any[]).find(x=>x.slug===s);return <a className="card" href={`/${s}`} key={s}><b>{p.h1}</b><p>{cleanSeoText(p.description)}</p><span>자세히 보기 →</span></a>})}</div></section>
 <section className="split section"><div><span className="eyebrow">실제 강의 화면</span><h2>교수의 설명 방식과 문제풀이 흐름을 확인하세요</h2><p>강의를 고를 때는 홍보 문구만 보기보다 실제 화면에서 판서량, 설명 속도, 문제를 풀어가는 순서를 확인하는 것이 좋습니다. 제공받은 강의 캡처를 활용해 수강 전 판단에 필요한 정보를 정리했습니다.</p><a className="textLink" href="/electric-engineer-online-course">전기기사 인강 선택 기준 보기 →</a></div><div className="imageGrid"><Image src="/images/lecture-2.jpg" width={800} height={430} alt="엔지니어랩 전기기사 실제 강의 화면"/><Image src="/images/lecture-4.jpg" width={800} height={430} alt="엔지니어랩 자격증 문제풀이 강의 화면"/></div></section>
 <section className="section"><div className="sectionTitle"><span>교수별 강의 정보</span><h2>교수 이름보다 실제 설명 방식을 비교하세요</h2><p>같은 자격증 강의라도 개념을 설명하는 깊이와 문제풀이 속도가 다를 수 있습니다. 교수별 페이지에서 실제 강의 자료와 선택 기준을 확인하세요.</p></div><div className="professors"><a href="/professor-jo-jungpil"><Image src="/images/prof-jo.jpg" width={980} height={645} alt="엔지니어랩 조경필 교수 강의 자료"/><b>조경필 교수 강의 가이드</b></a><a href="/professor-kim-sanghoon"><Image src="/images/prof-kim.jpg" width={980} height={645} alt="엔지니어랩 김상훈 교수 강의 자료"/><b>김상훈 교수 강의 가이드</b></a><a href="/professor-lee-jongoh"><Image src="/images/prof-lee.jpg" width={980} height={645} alt="엔지니어랩 이종오 교수 강의 자료"/><b>이종오 교수 강의 가이드</b></a></div></section>
 <section className="section review"><div><span className="eyebrow">합격생 후기 자료</span><h2>나와 조건이 비슷한 수험생의 학습 과정을 보세요</h2><p>합격 여부만 보는 것보다 직장 병행, 비전공, 재도전 등 자신의 상황과 가까운 사례에서 강의를 어떻게 활용했는지 확인하는 편이 참고 가치가 높습니다.</p><a className="textLink" href="/engineerlab-review">엔지니어랩 후기 보는 기준 →</a></div><div className="reviewImgs"><Image src="/images/review-1.jpg" width={640} height={360} alt="엔지니어랩 합격생 후기 영상 자료"/><Image src="/images/review-2.jpg" width={640} height={480} alt="전기 자격증 합격 후기 자료"/></div></section>
 <section className="section cbt"><div><Image src="/images/cbt-screen.jpg" width={1916} height={942} alt="전기기사 CBT 시험 화면 자료"/></div><div><span className="eyebrow">CBT 시험 준비</span><h2>화면 적응과 시간 배분도 따로 연습하세요</h2><p>종이 문제를 풀 때와 컴퓨터 화면에서 문제를 이동하며 푸는 방식은 체감이 다를 수 있습니다. CBT 화면 적응, 기출 반복, 제한시간 관리 방법을 별도 페이지에서 확인할 수 있습니다.</p><a className="textLink" href="/electric-engineer-cbt">전기기사 CBT 준비방법 →</a></div></section>
 <section className="section"><div className="sectionTitle"><span>학습 가이드</span><h2>검색 목적에 맞는 공부법을 골라보세요</h2></div><div className="cards">{guides.map(s=>{const p=(pages as any[]).find(x=>x.slug===s);return <a className="card" href={`/${s}`} key={s}><b>{p.h1}</b><p>{cleanSeoText(p.description)}</p><span>학습 가이드 보기 →</span></a>})}</div></section>
 <section id="apply" className="section finalCta"><h2>강좌를 정했다면 할인코드 e1572 적용 여부 확인</h2><p>강좌 구성과 수강기간을 먼저 확인한 뒤 결제 단계에서 <b>e1572</b>를 입력해 적용 결과와 최종 금액을 확인하세요. 상품과 이벤트 시점에 따라 할인 조건은 달라질 수 있습니다.</p><Coupon/></section>
 </main>}
