import Image from "next/image";
import Coupon from "../components/Coupon";
import SuccessVideos from "../components/SuccessVideos";
import pages from "../data/pages.json";
import {cleanSeoText} from "../lib/seoText";

const picks=["electric-engineer","electric-industrial-engineer","electric-construction-engineer","fire-equipment-engineer","public-enterprise-electric"];
const guides=["electric-engineer-beginner","electric-engineer-written","electric-engineer-practical","electric-engineer-cbt","certificate-study-plan","lecture-selection-guide"];

export default function Home(){return <main>
 <section className="homeHero"><div><span className="eyebrow">2026 엔지니어랩 할인·수강 정보</span><h1>엔지니어랩 할인코드 <em>e1572</em><br/><b>총 6만원 할인</b> 받고 시작하세요</h1><p>전기기사·전기산업기사·전기공사기사·소방설비기사 인강을 비교하고, 교수별 강의 특징·실제 강의 화면·CBT·공부법까지 확인한 뒤 할인코드 e1572로 6만원 할인 혜택을 확인하세요.</p><Coupon/></div><div className="heroImage"><Image src="/images/prof-jo.jpg" alt="엔지니어랩 전기기사 강의와 e1572 6만원 할인 안내" fill priority sizes="(max-width:800px) 100vw, 45vw"/></div></section>
 <section className="benefitStrip"><div><b>60,000원</b><span>e1572 할인 혜택</span></div><div><b>33개</b><span>자격증·공부법 상세 가이드</span></div><div><b>3편</b><span>합격생 영상 바로 보기</span></div><div><b>1번에</b><span>강의·교수·CBT·후기 비교</span></div></section>
 <section className="section discountGuide"><div className="sectionTitle"><span>e1572 할인 적용 순서</span><h2>코드만 보여주지 않고, 실제 적용 흐름까지 확인하세요</h2><p>강좌를 먼저 고른 뒤 코드 입력과 할인 적용 결과를 확인하는 순서가 가장 깔끔합니다. 결제 완료 전 최종 금액을 확인하세요.</p></div><div className="cards"><div className="card"><b>01. e1572 복사</b><p>영문 소문자 e와 숫자 1572를 그대로 복사해 오타를 줄입니다.</p></div><div className="card"><b>02. 원하는 강좌 선택</b><p>전기기사·전기산업기사·전기공사기사·소방설비기사 등 목표 시험에 맞는 강좌와 수강기간을 먼저 확인합니다.</p></div><div className="card"><b>03. 6만원 할인 확인</b><p>회원가입 또는 수강신청 단계에서 e1572를 입력하고, 결제 전 60,000원 할인 적용 여부와 최종 금액을 확인합니다.</p></div></div><p className="notice">※ 할인 적용 대상과 이벤트 조건은 시점과 상품에 따라 달라질 수 있으므로 공식 결제 화면의 최종 조건을 기준으로 확인하세요.</p></section>
 <section className="section"><div className="sectionTitle"><span>자격증별 강의 가이드</span><h2>준비하는 시험에 맞춰 먼저 확인하세요</h2><p>시험별로 필기·실기 구성과 공부 순서가 다릅니다. 목표 자격증을 선택해 강좌 선택 기준과 학습 방법을 확인할 수 있습니다.</p></div><div className="cards">{picks.map(s=>{const p=(pages as any[]).find(x=>x.slug===s);return <a className="card" href={`/${s}`} key={s}><b>{p.h1}</b><p>{cleanSeoText(p.description)}</p><span>자세히 보기 →</span></a>})}</div></section>
 <section className="split section"><div><span className="eyebrow">실제 강의 화면</span><h2>교수의 설명 방식과 문제풀이 흐름을 확인하세요</h2><p>강의를 고를 때는 홍보 문구만 보기보다 실제 화면에서 판서량, 설명 속도, 문제를 풀어가는 순서를 확인하는 것이 좋습니다. 제공받은 강의 캡처를 활용해 수강 전 판단에 필요한 정보를 정리했습니다.</p><a className="textLink" href="/electric-engineer-online-course">전기기사 인강 선택 기준 보기 →</a></div><div className="imageGrid"><Image src="/images/lecture-2.jpg" width={800} height={430} alt="엔지니어랩 전기기사 실제 강의 화면"/><Image src="/images/lecture-4.jpg" width={800} height={430} alt="엔지니어랩 자격증 문제풀이 강의 화면"/></div></section>
 <section className="section"><div className="sectionTitle"><span>교수별 강의 정보</span><h2>교수 이름보다 실제 설명 방식을 비교하세요</h2><p>같은 자격증 강의라도 개념을 설명하는 깊이와 문제풀이 속도가 다를 수 있습니다. 교수별 페이지에서 실제 강의 자료와 선택 기준을 확인하세요.</p></div><div className="professors"><a href="/professor-jo-jungpil"><Image src="/images/prof-jo.jpg" width={980} height={645} alt="엔지니어랩 조경필 교수 강의 자료"/><b>조경필 교수 강의 가이드</b></a><a href="/professor-kim-sanghoon"><Image src="/images/prof-kim.jpg" width={980} height={645} alt="엔지니어랩 김상훈 교수 강의 자료"/><b>김상훈 교수 강의 가이드</b></a><a href="/professor-lee-jongoh"><Image src="/images/prof-lee.jpg" width={980} height={645} alt="엔지니어랩 이종오 교수 강의 자료"/><b>이종오 교수 강의 가이드</b></a></div></section>
 <section className="section videoSection"><div className="sectionTitle"><span>합격생 영상</span><h2>실제 합격생의 학습 경험을 영상으로 확인하세요</h2><p>직장 병행, 비전공, 재도전처럼 자신의 상황과 가까운 사례에서 어떤 방식으로 준비했는지 직접 확인할 수 있도록 합격생 영상을 연결했습니다.</p><a className="textLink" href="/engineerlab-review">엔지니어랩 후기 보는 기준 →</a></div><SuccessVideos/></section>
 <section className="section cbt"><div><Image src="/images/cbt-screen.jpg" width={1916} height={942} alt="전기기사 CBT 시험 화면 자료"/></div><div><span className="eyebrow">CBT 시험 준비</span><h2>화면 적응과 시간 배분도 따로 연습하세요</h2><p>종이 문제를 풀 때와 컴퓨터 화면에서 문제를 이동하며 푸는 방식은 체감이 다를 수 있습니다. CBT 화면 적응, 기출 반복, 제한시간 관리 방법을 별도 페이지에서 확인할 수 있습니다.</p><a className="textLink" href="/electric-engineer-cbt">전기기사 CBT 준비방법 →</a></div></section>
 <section className="section"><div className="sectionTitle"><span>학습 가이드</span><h2>검색 목적에 맞는 공부법을 골라보세요</h2></div><div className="cards">{guides.map(s=>{const p=(pages as any[]).find(x=>x.slug===s);return <a className="card" href={`/${s}`} key={s}><b>{p.h1}</b><p>{cleanSeoText(p.description)}</p><span>학습 가이드 보기 →</span></a>})}</div></section>
 <section id="apply" className="section finalCta"><span className="eyebrow">최종 결제 전 체크</span><h2>엔지니어랩 할인코드 e1572로 6만원 할인 확인</h2><p>강좌 구성과 수강기간을 먼저 확인한 뒤 회원가입 또는 수강신청 단계에서 <b>e1572</b>를 입력하세요. 결제를 완료하기 전에 <b>60,000원 할인 적용 여부</b>와 최종 결제 금액을 확인하면 됩니다.</p><Coupon/></section>
 </main>}
